### ISSUE TITLE
Failing tests for 20x20

### ISSUE THREAD

**Issue by OzBob** [miciek/web-snake-react-bacon#1]
Hi,

Thank you for your code and samples - I am using it to learn RxJS and React.

Trying to follow along with https://michalplachta.com/2016/05/11/reactive-ui-by-example/
is hard. The code has moved forward and the samples in the article are a bit old.

e.g ref to main.jsx

I stopped trying to use the 'tree/workshop-init' from the start and just run the completed code.

Also, "npm run test" has failing tests if app.js is a 20x20 board, if update to 10x10 and run tests again. All OK.

**Comment by miciek** [comment]
Thanks @OzBob I have updated the post and it now includes link to the exact commit that enables you to follow instructions in the post https://github.com/miciek/web-snake-react-bacon/tree/c20f6102f1485a289cec78ba3c6cc40800bb7158

The tests are simple snapshot tests that guards me against regression. 10x10 is hardcoded in snapshots :)

Let me know if you have any more troubles.
